# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
# Build settings:
theme: jekyll-theme-cayman

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: US Roadtrip Summer 2019
email: jannis.born@gmx.de, ninawiedemann999@gmail.com
description: An epic 3-week roadtrip in Western US including 9 national parks! #>- # this means to ignore newlines until "baseurl:"

# Variables:
header: /assets/images/header.jpg
twitter_username: jannisborn
github_username:  jannisborn





